config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'links#show', :as => 'home'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'register' => 'users#new', :as => 'register'
  root :to => 'sessions#new'
  resources :users
  resources :sessions
end

app/models/link.rb
class Link < ActiveRecord::Base
    belongs_to :user    

    def self.get_available_link
    	Link.where("user_id IS NULL").order("RANDOM()").first
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_one :link, :dependent => :nullify
    attr_accessor :password
    validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :email
    validates_uniqueness_of :email
    validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :on => :create
    validates_format_of :password, with: /\A^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$\z/i, :on => :create, :message => "should be minimum 8 characters, containing atleast one uppercase letter, one lowercase letter and a digit"
    validates_format_of :name, with: /\A[A-Za-z][A-Za-z\'\ \-]*\z/i, :on => :create, :message => "can contain only alphabets and apostrophe"

    before_save :encrypt_password

    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
            user
        else
            nil
        end
    end
    
    def encrypt_password
        if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        end
    end        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_login

  def show
  	@link = Link.find_by_user_id(session[:user_id])  		
  end

  private
  def require_login
    if current_user.nil?
      flash[:error] = "You must be logged in to access this section"
      redirect_to "/login"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def index
    redirect_to '/login'
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
        session[:user_id] = user.id
        redirect_to '/home', :notice => "Successfully logged in"
    else
        flash.now.alert = "Invalid credentials"
        render "new"
    end
  end
    
  def destroy
    session[:user_id] = nil
    redirect_to '/login', :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logout
  def new
    @user = User.new
  end

  def index
    redirect_to '/register'
  end

  def create
    @user = User.new(user_params)
    if @user.save
    	# User registered, now randomly assign a link
    	available_link = Link.get_available_link  
    	@link_assigned = false  	
    	if available_link # Go ahead and assign the link to the user in case of availability, else skip
    		link_assigned = true
    		available_link.user_id = @user.id
    		available_link.save
    	end 
    	#Continue with registration irrespective of whether a random link was available or not    	
    	UserMailer.welcome_email(@user, link_assigned).deliver_now
        redirect_to "/login", :notice => 'Registered successfully!'
    else
        render "new"
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  private
  def require_logout
    if !current_user.nil?
        redirect_to "/home"
    else
        nil
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Random Link Assigner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header-container" class="row">
		<div class="row">
			<div class="col-xs-1">&nbsp;</div>
			<div class="col-xs-6 white-text title">&nbsp;Random Link Assigner
			</div>		
			<div class="col-xs-1">&nbsp;</div>
		    <% if current_user %>
		        <div class="col-xs-4"><span class='white-text'>Hello, <em><%= current_user.name %></em>!</span>&nbsp;&nbsp;
		        <%= link_to "Logout", logout_path, class: 'black' %></div>
		    <% else %>
		        <div class="col-xs-4"><%= link_to "Register", register_path, class: 'black' %>
		        <span class='white-text'>&nbsp;or&nbsp;</span><%= link_to "Login", login_path, class: 'black' %></div>
		    <% end %>
		    </div>
	    </div>
    </div>
<div class="container">	
	<div id="main-container" class="container-fluid">
		
	    <div id="alert-container" class="row">
			<% flash.each do |name, msg| %>
				<div class="alert alert-danger alert-dismissible" role="alert">
				 	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>  
				</div>    
			<% end %>
		</div>
		<div id="content-container" class="row">
			<%= yield %>
		</div>
	</div>
</div>
</body>
</html>

app/views/links/show.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Your random link
	</div>
  	<div class="panel-body">
  		<% if !@link.blank? %>    	
	        Your random url is <a href='<%= @link.url %>' target="_blank"><%= @link.url %></a>
	    <% else %>
	        Sorry, you have not been assigned a link yet. Don't worry, we'll get one for you soon
    	<% end %>
  	</div>
</div>

<h3></h3>
<p>
    
</p>

app/views/users/new.html.erb
<h3>Register</h3>
<%= form_for @user do |u| %>
    <% if @user.errors.any? %>
        <% for message in @user.errors.full_messages %>
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <%= message %>
            </div>         
        <% end %>
    <% end %>
    <div class="form-group">
        <%= u.label :name %><br/>
        <%= u.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= u.label :email %><br/>
        <%= u.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= u.label :password %><br/>
        <%= u.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= u.label :password_confirmation %><br/>
        <%= u.password_field :password_confirmation, class: 'form-control' %>
    </div>    
    <button type="submit" class="btn btn-primary">
    	Register
    </button>    
<% end %>